apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'flask-backend'
        metrics_path: /metrics
        static_configs:
          - targets: ['flask-backend:5000']

