replicaCount: 1

image:
  repository: your-registry/your-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: false
  host: backend.local
  annotations: {}
  tls: []

resources: {}

env: {}
