apiVersion: v1
kind: Service
metadata:
  name: flask-backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"

spec:
  selector:
    app: flask-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
