apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
spec: 
  template:
    spec:
      containers:
        - name: flask-backend
          env:
            - name: ENVIRONMENT
              value: "development"
            - name: DEBUG
              value: "1"

